### ISSUE TITLE
Generate Surface Styles and Generate State Layers not working

### ISSUE THREAD

**Issue by andrewhainen-slalom** [material-foundation/material-theme-builder#149]
When updating a primary color, the Outlined buttons clearly show that the State Layers didn't update to the brown-ish
![Screenshot 2023-03-30 at 10 15 36 AM](https://user-images.githubusercontent.com/84816050/228865270-c92b4b6a-c699-4052-8c21-21114cbadf0e.png)

**Comment by PrattiDev** [comment]
You seem to have a very old version of the UI kit. The Figma plugin no longer generates `read-only` style groups, which is what is failing to update in your file.

Instead of `M3/read-only/light/`, the new structure wants `M3/state-layers/light/`

![image](https://user-images.githubusercontent.com/17130024/229172662-774834f9-df44-4d2e-a5e2-56e5c7ab4097.png)

You can double click on the color group in the Figma sidebar to rename it. 

![image](https://user-images.githubusercontent.com/17130024/229173207-446c30f2-bba0-45a8-90e4-420831987eb3.png))

**Comment by andrewhainen-slalom** [comment]
Got it, thank you for the info. The team has decided to switch to MUI, but regardless - thank you for this info
