### ISSUE TITLE
[Feature request] Generate the theme and color from image

### ISSUE THREAD

**Issue by jarvis1801** [material-foundation/material-theme-builder#189]
**Is your feature request related to a problem? Please describe.**
Generate the theme and color from image, just like dynamic color

**Describe the solution you'd like**
in website user can input image for this function, and output the xml, jetpack ... format for colors and theme

**Comment by jarvis1801** [comment]
I think this feature will help the developer who is not good for design
and they will get the better design for generated dynamic color for the specific application
then will increase the UX

**Comment by margeeta** [comment]
Hello, thank you for the request. 
Both web and Figma versions support image color extraction. 
In Figma, there is an additional toggle to utilize the content color algorithm, otherwise the first toggle option is to simulate wallpaper color.

![image-color-extraction](https://github.com/material-foundation/material-theme-builder/assets/10263978/e6f44130-e6a2-42ac-8680-9533fcaa9efb)
