### ISSUE TITLE
Unchecking "Palette Variables" does nothing

### ISSUE THREAD

**Issue by PrattiDev** [material-foundation/material-theme-builder#232]
**Describe the bug**
I cannot stop MTB 2.0 from generating variables.

**To Reproduce**
1. Uncheck the "Palette Variables" option in Settings.
2. The plugin will still generate them regardless.

**Expected behavior**
MTB would stop generating variables.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 2.0

**Additional notes**
Due to Figma prioritizing variables in the style panel, the plugin has been harder to use in the meantime. I hope it can be fixed soon. The update is great otherwise!

**Comment by margeeta** [comment]
Hello! Thanks for the feedback, we're really excited about the update. 
The "Palette Variables" setting is for generating (or not generating) reference tokens. 

Styles will still be priority overall for MTB for awhile due to modes constrained to paid plans. But there will be refinement, like turning styles or variables off, as we gather more feedback on usage and Figma rolls out more variable features. 
In the meantime, there is a variable discussion thread, closing this issue for now and recording feedback: https://github.com/material-foundation/material-theme-builder/discussions/207
