### ISSUE TITLE
Can't export Dynamic theme

### ISSUE THREAD

**Issue by Slion** [material-foundation/material-theme-builder#29]
I was hoping I could export a Dynamic theme but the export menu is only there when doing Custom theme.
Also custom theme needs three colors rather than just the one for the Dynamic theme.
I would love to have the ability to specify the one color for the Dynamic theme and be able to export it.

**Comment by margeeta** [comment]
Thanks @Slion!

The export option is only in custom, since dynamic is meant for visualizing dynamic color within mockups. We hope you color is expressed through user generated colors!

But if you come across a color theme created in dynamic and would like to use that as your custom or fallback theme, it is possible to export it under Custom: switching to custom will translate the theme to a custom one with key colors setup.

Also when in Custom, if you only have one brand color, or would like to create a full color scheme from just the one color: Primary acts as the source color, the rest will generate from the primary.

**Comment by Slion** [comment]
> Also when in Custom, if you only have one brand color, or would like to create a full color scheme from just the one color: Primary acts as the source color, the rest will generate from the primary.

I see, I thought this was not working but I was wrong it works just fine. My bad, thanks for the help.
