### ISSUE TITLE
Is that expected behavior that updates natural color drastically?

### ISSUE THREAD

**Issue by sundaycrafts** [material-foundation/material-theme-builder#84]
**Describe the bug**

On [Material theme builder on the Web](https://m3.material.io/theme-builder#/custom) and Figma plugin, the natural color changes drastically when I modify its parameter. And I can't restore the default color palette.

**To Reproduce**
Steps to reproduce the behavior (see screen shot below):
1. Go to [Material theme builder on the Web](https://m3.material.io/theme-builder#/custom)
2. Click on "Neutral"
3. Change the Hue value by 1 point.
4. Neutral color is drastically changed.

**Expected behavior**
I don't know if this is expected behavior or not. But users must expect to restore the default state, at least.

**Screenshots**
[Default color paletto]
![image](https://user-images.githubusercontent.com/4732821/190988560-505f1a2f-7cb1-4852-8e92-93a679dfbdae.png)

[After Updated 294 (293.03761206699426 as precise) -> 293]
![image](https://user-images.githubusercontent.com/4732821/190988763-dd8ac073-a11a-48bb-864f-72d3fcd4af7e.png)

**Desktop (please complete the following information):**
 - OS: macOS (12.3.1)
 - Browser: Firefox / Chrome
 - Version: [Firefox] 104.0.2 (64-bit) / [Chrome] 105.0.5195.125 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
NA

**Comment by andaja** [comment]
I was stuck at this as well. on the web and in Figma plugin it wrests chroma/saturation unpredictably high for most colors probably mostly when the primary is saturated. Especially enigmatic is the sudden switch to bright cyan if chroma = 0. 

On a related note, it tunes the hue of the some colors +/- but I expect it can be due to some special perceptive magic. Though it looks like the mid-contrast rules are broken here as well as in WCAG 2. So I am not sure if it is intentional. 

![image](https://user-images.githubusercontent.com/3940137/190992632-9353b6f7-d280-45dd-9a1f-f3c5eaa0d043.png)

**Comment by pbroom** [comment]
I have the exact same problem. Chroma and Tone seem to jump to an unknown locked position whenever I try to edit them.
