### ISSUE TITLE
HCT Color Picker weird behavior

### ISSUE THREAD

**Issue by ivanbachev** [material-foundation/material-theme-builder#89]
**Describe the bug**
The HCT Color Picker available on https://m3.material.io/theme-builder#/custom acts in a very unpredictable way.

**To Reproduce**
When I click on a color from the Core colors and show the tonal palettes I then tweak the color Chroma and Tone values but these no longer produce consistent results. 

**Screenshots**
Consider the following case when the Hue preview changes unexpectedly when the Chroma value is set to 0. Note that the actual Hue value shown in the following example does not changed - but the preview does. 

![m3 material io_theme-builder (1) ](https://user-images.githubusercontent.com/1560160/199740050-43c0dc8d-c742-4ba3-b2ac-8e0d1a8ea3dc.png ) ![m3 material io_theme-builder](https://user-images.githubusercontent.com/1560160/199740089-9ad9402f-ccd1-4f0d-b082-40011fff0eb0.png)

**Desktop:**
 - OS: macOS Big Sur
 - Browser: Google Chrome
 - Version: Version 107.0.5304.87

**Comment by margeeta** [comment]
Hi @ivanbachev! Thanks for the issue. 
This is due to the color algorithm trying to adjust when at 0, which ends up creating a blue effect instead of the desaturated version of the entered Hue. You should notice changing the chroma to 1 will usually adjust it to the proper Hue. 

In this instance was the desired result monochrome or grey for tertiary?
